"""Load the live creature seed roster used by action seeding.

The species seed folder is the source of truth. The generated C# catalog remains
available only as an explicit legacy compatibility input for older fixtures.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping, Sequence

from ...creatures.family.consolidate import FamilyCandidateInput, consolidate
from .curation import curated_traits
from .ladders import (
    RARITY_LADDER,
    RARITY_ORDINAL,
    TRAIT_POOL,
)

# The family-label normalisation now lives in the shared leaf, because the creatures runner's
# fail-closed guard has to judge family labels exactly as this consumer does. Restating the regex
# on either side would be two implementations free to drift from each other - measured 2026-10-04,
# when 36 Chinese-language labels across 13 entries were written and every one would be refused here.
from seedsmith.ladders import normalize_family_key

__all__ = [
    "SpeciesRow", "RARITY_LADDER", "TRAIT_POOL", "load_catalog", "load_live_records",
    "derive_live_family_assignments", "CATALOG_PATH", "LEGACY_CATALOG_PATH",
]

REPO_ROOT = Path(__file__).resolve().parents[6]

# `REPO_ROOT`-relative joins below ask which repository actually carries the path. A prefix-keyed
# rewrite is wrong: `data`, `data/seed` and `data/seed/creatures` all resolve back to gk-forge,
# because nearest-match-wins and gk-forge owns its own generator inputs. `or REPO_ROOT` is
# load-bearing - `owning_base` returns None for a path no repository carries, where
# `content_root()` would RAISE.

from ....workspace_roots import owning_base  # noqa: E402


def _owned(relative: str) -> "Path":
    """The repository carrying `relative`, joined to it; this one when none carries it."""
    return (owning_base(relative, REPO_ROOT) or REPO_ROOT) / relative

CATALOG_PATH = _owned("data/seed/creatures/species")
LEGACY_CATALOG_PATH = _owned("src/FusionRpg.Core/Creatures/CreatureSpeciesCatalog.Generated.cs")

#: The curated family registry — this repo's OWN human-owned family vocabulary, read fresh and
#: never transcribed. It is the second of the two committed corroboration sources the head-noun
#: merge consults (`family/consolidate.py`'s module docstring names both). It is not redundant with
#: the corpus's own labels: `pea` groups 9 real species and is a curated family, yet no species ever
#: authored the bare label `pea` — every one of them wrote `pea-shooter` or `double-peashooter`, so
#: without the registry the corroboration-gated merge would stop stripping `pea-shooter` and split a
#: real family in two.
#:
#: Read here, in the module that already resolves the seed root, and passed DOWN as a parameter —
#: `consolidate` is a leaf and resolving a path from it is how a leaf joins an import cycle.
FAMILY_REGISTRY_PATH = _owned("data/seed/creatures/_registry/families.v1.json")

# `RARITY_LADDER` / `TRAIT_POOL` now live in `ladders.py` (a leaf both this module and `curation.py`
# import from — see that module's docstring for why the shared copy fixes the drift risk). They are
# re-exported above so every existing importer of `catalog.RARITY_LADDER` keeps working unchanged.

_ELEMENT_ID = {
    "Fire": "fire", "Ice": "ice", "Air": "air", "Earth": "earth", "Light": "light", "Dark": "dark",
}

# One `new() { ... }` object per species, on one line (the generator's own convention — see the
# file's own `<auto-generated>` header: "Regenerate: dotnet run --project gk-forge/tools/CreatureCatalogGen").
_ROW_RE = re.compile(
    r'SpeciesId\s*=\s*"(?P<id>[a-z0-9]+)".*?'
    r'ElementPrimary\s*=\s*ElementTypeId\.(?P<elem_primary>\w+).*?'
    r'ElementSecondary\s*=\s*(?:ElementTypeId\.(?P<elem_secondary>\w+)|null).*?'
    r'BaseRarity\s*=\s*CreatureRarity\.(?P<rarity>\w+).*?'
    r'TraitPool\s*=\s*new\[\]\s*\{\s*(?P<traits>[^}]*)\s*\}',
)
_TRAIT_STR_RE = re.compile(r'"([a-z-]+)"')

#: Where one word of a committed CamelCase `speciesId` ends and the next begins: a run of capitals
#: (`PDF` -> one token), a capitalised word (`Mine`), or a lowercase run. This is the game's own
#: record of its own taxonomy, not a word list: `PeaMine` splits to `pea`/`mine` and `NutBlover` to
#: `nut`/`blover` with nothing hardcoded. `re` finds the humps; no morphology is inferred.
_CAMEL_SPLIT = re.compile(r"[A-Z]+(?![a-z])|[A-Z][a-z0-9]*|[a-z0-9]+")

# CreatureRarity enum member name -> ladder id (CreatureRarityIds.ToId, CreatureRarity.cs:52-65). The C#
# source spells the member in PascalCase; the ladder id is the same word lower-cased in every case
# here (Chaff -> "chaff", Sunwoven -> "sunwoven", ...), so a plain `.lower()` is the whole map —
# asserted by this module's own tests rather than assumed.
_RARITY_MEMBER_TO_ID = {rid.capitalize(): rid for rid in RARITY_LADDER}


@dataclass(frozen=True)
class SpeciesRow:
    species_id: str                     # lower-case, the canonical key (spec §3 step 1)
    element_primary: str                # one of ActorElementTypes' 6 ids
    element_secondary: "str | None"     # None when the species is pure (spec's own "none")
    rarity: str                         # the LADDER id — never the legacy band (spec §3 step 2)
    rarity_ordinal: int                 # CreatureRarity.cs declaration order, 0..9
    traits: "tuple[str, ...]"           # the CLOSED 14-trait pool (curated, `curation.py`)


def _load_legacy_catalog(path: Path) -> "list[SpeciesRow]":
    """Parse an explicitly supplied legacy `.cs` roster for compatibility fixtures."""
    text = path.read_text(encoding="utf-8")
    rows: "list[SpeciesRow]" = []
    seen: "set[str]" = set()
    for m in _ROW_RE.finditer(text):
        sid = m.group("id")
        if sid in seen:
            raise ValueError(f"{path}: duplicate SpeciesId {sid!r} in the catalog")
        seen.add(sid)

        elem_primary = _ELEMENT_ID.get(m.group("elem_primary"))
        if elem_primary is None:
            raise ValueError(f"{path}: species {sid!r} — unknown ElementPrimary "
                             f"{m.group('elem_primary')!r}")
        elem_secondary_raw = m.group("elem_secondary")
        elem_secondary = _ELEMENT_ID.get(elem_secondary_raw) if elem_secondary_raw else None
        if elem_secondary_raw and elem_secondary is None:
            raise ValueError(f"{path}: species {sid!r} — unknown ElementSecondary "
                             f"{elem_secondary_raw!r}")

        rarity_member = m.group("rarity")
        rarity_id = _RARITY_MEMBER_TO_ID.get(rarity_member)
        if rarity_id is None:
            raise ValueError(f"{path}: species {sid!r} — unknown BaseRarity {rarity_member!r}")

        traits = tuple(_TRAIT_STR_RE.findall(m.group("traits")))
        unknown_traits = [t for t in traits if t not in TRAIT_POOL]
        if unknown_traits:
            raise ValueError(f"{path}: species {sid!r} — trait(s) {unknown_traits} outside the "
                             f"14-member closed pool")

        rows.append(SpeciesRow(
            species_id=sid, element_primary=elem_primary, element_secondary=elem_secondary,
            rarity=rarity_id, rarity_ordinal=RARITY_ORDINAL[rarity_id], traits=traits,
        ))
    if not rows:
        raise ValueError(f"{path}: matched zero species rows — the row pattern no longer fits "
                         f"the live file's shape")
    return rows


def load_live_records(root: Path = CATALOG_PATH) -> "list[dict[str, object]]":
    """Read every live species record from the seed folder in stable path order."""
    if not root.is_dir():
        raise ValueError(f"{root}: live species seed directory does not exist")

    records: "list[dict[str, object]]" = []
    seen: "set[str]" = set()
    for path in sorted(root.rglob("*.json")):
        if path.name == "_index.json":
            continue
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise ValueError(f"{path}: invalid JSON: {exc}") from exc

        entries = payload if isinstance(payload, list) else [payload]
        for entry in entries:
            if not isinstance(entry, dict):
                raise ValueError(f"{path}: species record must be an object")
            raw_id = entry.get("speciesId")
            if not isinstance(raw_id, str) or not raw_id.strip():
                raise ValueError(f"{path}: species record is missing speciesId")
            species_id = raw_id.strip().lower()
            if species_id in seen:
                raise ValueError(f"{path}: duplicate speciesId {species_id!r}")
            seen.add(species_id)
            # `_rawSpeciesId` is the id AS COMMITTED, casing intact. `speciesId` is lower-cased for
            # the canonical key, which is correct for every consumer and fatal for the one thing
            # that reads the game's own name taxonomy: `PeaMine` is two words and `peamine` is one.
            # Preserved under an underscore-prefixed name so no schema consumer mistakes it for a
            # field (the sibling key `_sourcePath` sets the precedent).
            records.append({
                **entry, "speciesId": species_id, "_rawSpeciesId": raw_id.strip(),
                "_sourcePath": str(path),
            })

    if not records:
        raise ValueError(f"{root}: live species seed directory contains no species records")
    return records


def _live_row(record: dict[str, object]) -> SpeciesRow:
    path = record.get("_sourcePath", "live species seed")
    species_id = record["speciesId"]
    if not isinstance(species_id, str):
        raise ValueError(f"{path}: speciesId must be a string")

    primary = record.get("elementPrimary")
    secondary = record.get("elementSecondary")
    valid_elements = {"fire", "ice", "air", "earth", "light", "dark"}
    primary_id = primary.lower() if isinstance(primary, str) else ""
    secondary_id = secondary.lower() if isinstance(secondary, str) and secondary.lower() != "none" else None
    if primary_id not in valid_elements:
        raise ValueError(f"{path}: species {species_id!r} has unknown elementPrimary {primary!r}")
    if secondary_id is not None and secondary_id not in valid_elements:
        raise ValueError(f"{path}: species {species_id!r} has unknown elementSecondary {secondary!r}")
    if secondary_id == primary_id:
        secondary_id = None

    rarity = record.get("rarity")
    rarity_id = rarity.lower() if isinstance(rarity, str) else ""
    if rarity_id not in RARITY_ORDINAL:
        raise ValueError(f"{path}: species {species_id!r} has unknown rarity {rarity!r}")

    # Shape guard on the seed's OWN open flavor `traits` field. It is NOT scored — the closed pool
    # below is (see `curation.py` for the full defect account) — but a malformed seed should still
    # fail loudly here rather than be silently ignored.
    if not isinstance(record.get("traits", []), list):
        raise ValueError(f"{path}: species {species_id!r} traits must be a list")

    # The live seed's `traits` field is open flavor text (measured 2026-09-11: 2,312 distinct
    # tokens, one of which is a closed-pool member). Score the CLOSED pool the game actually gives
    # this species — `CreatureTraitPoolCuration.PickFor`'s own bridge, mirrored in `curation.py`. See
    # `curation.py` for the full defect account.
    game_type_id = record.get("gameTypeId")
    traits = curated_traits(
        species_id, rarity_id,
        game_type_id if isinstance(game_type_id, int) and not isinstance(game_type_id, bool) else 0)
    return SpeciesRow(
        species_id=species_id,
        element_primary=primary_id,
        element_secondary=secondary_id,
        rarity=rarity_id,
        rarity_ordinal=RARITY_ORDINAL[rarity_id],
        traits=traits,
    )


def load_curated_family_terms(path: Path = FAMILY_REGISTRY_PATH) -> "frozenset[str]":
    """The curated `families.v1.json` family ids, or an empty set when the registry is absent.

    Empty rather than raising is deliberate and asymmetric with the guards above: this set only ever
    WIDENS the set of heads the merge may strip, so a missing registry degrades the grouping to
    "corroborate from the corpus's own labels alone" instead of failing a whole corpus load. That is
    the same weaker-but-correct posture `load_synonyms`' absence would take, and it is why the
    registry is corroboration and not authority.
    """
    if not path.is_file():
        return frozenset()
    doc = json.loads(path.read_text(encoding="utf-8"))
    families = doc.get("families")
    return frozenset(families) if isinstance(families, dict) else frozenset()


#: Species whose family was filled by `resolve_unresolved_family` during the LAST
#: `derive_live_family_assignments` call in this process, rewritten on every call. Written HERE and
#: read by anyone who needs to know which families carry no model judgment; it exists because that
#: function's return type is the assignments map every existing caller already expects, and the
#: anchor's `_provenance.confidence` is written by the runner, not from here.
#:
#: This is the SET, not the stamp. The honest-provenance tag those species owe is
#: `"deterministic-fallback"` — the same one `creatures/anchor/derive.py`'s `resolve_unresolved_*`
#: family stamps, and never a value disguised as a model judgment — but this module does not write
#: it, and claiming otherwise here would be a comment asserting a fact no code line establishes.
FALLBACK_SURFACE: "list[str]" = []


def _key_owners(
    assignments: "Mapping[str, Sequence[str]]",
) -> "dict[str, set[str]]":
    """Which species land on each consolidated family key — the input
    `family/fallback.py`'s artefact test is stated in terms of.

    The audit's structural test ("does this key ever bucket more than one thing?") is a property of
    this mapping, and asking it per species rather than as a global set is what stops a species from
    being the only reason its own family looks corroborated.
    """
    owners: "dict[str, set[str]]" = {}
    for species_id, families in assignments.items():
        for family in families:
            owners.setdefault(family, set()).add(species_id)
    return owners


def _committed_name_tokens(records: "Sequence[dict]") -> "dict[str, tuple[str, ...]]":
    """Each species' OWN committed CamelCase `speciesId`, split into its own words.

    `load_live_records` lower-cases `speciesId` on the way out (it is the canonical key), which
    destroys the one committed signal this derivation needs: `PeaMine` is two words, `peamine` is
    one. So this reads the id off the record as loaded — `load_live_records` keeps the whole original
    entry under the spread — and splits on the ORIGINAL casing held in `_rawSpeciesId`.

    No word list, no morphology, no English: `re` finds the camel humps, which are the game's own
    record of where one creature word ends and the next begins.
    """
    out: "dict[str, tuple[str, ...]]" = {}
    for record in records:
        raw = record.get("_rawSpeciesId") or record["speciesId"]
        tokens = tuple(dict.fromkeys(t.lower() for t in _CAMEL_SPLIT.findall(str(raw)) if t))
        out[str(record["speciesId"])] = tokens
    return out


def derive_live_family_assignments(root: Path = CATALOG_PATH) -> "dict[str, list[str]]":
    """Derive species-to-family memberships from the live species records.

    Two refusals, in this order, and the distinction between them is the design:

      * A species carrying NO live family label at all still raises `has no family`. That raise is
        the contract which made 338 family-less species visible in the first place; relaxing it is
        not this change's job and a silent default would hide the next one.
      * A species whose labels are all REFUSED AS ARTEFACTS is handed to `resolve_unresolved_family`,
        which derives a real grouping from committed data. If that derivation cannot be made, the
        species keeps whatever label it had — never emptied, never invented.

    The fallback reads the CONSOLIDATED result, because "is this family corroborated" is a property
    of the consolidated vocabulary (does any other species share the key?), which only `consolidate`
    can answer.
    """
    from ...creatures.family.fallback import resolve_unresolved_family

    curated = load_curated_family_terms()
    records = load_live_records(root)
    candidates: "list[FamilyCandidateInput]" = []
    for record in records:
        raw_families = record.get("family", [])
        if isinstance(raw_families, str):
            raw_families = [raw_families]
        if not isinstance(raw_families, list):
            raise ValueError(f"{record['_sourcePath']}: family must be a list")
        labels = sorted({str(label).strip() for label in raw_families if str(label).strip()})
        if not labels:
            raise ValueError(f"{record['_sourcePath']}: species {record['speciesId']!r} has no family")
        for label in labels:
            candidates.append(FamilyCandidateInput(
                species_id=str(record["speciesId"]), label=label,
                native_label=label, basis="text",
            ))

    assignments = consolidate(candidates, established_terms=curated).assignments
    name_tokens = _committed_name_tokens(records)
    owners = _key_owners(assignments)

    del FALLBACK_SURFACE[:]
    out: "dict[str, list[str]]" = {}
    for species_id in sorted(assignments):
        resolved, was_deterministic = resolve_unresolved_family(
            assignments[species_id],
            species_id=species_id,
            name_tokens=name_tokens.get(species_id, ()),
            curated_terms=curated,
            key_owners=owners,
        )
        out[species_id] = sorted(set(resolved))
        if was_deterministic:
            FALLBACK_SURFACE.append(species_id)
    return out


def load_catalog(path: Path = CATALOG_PATH) -> "list[SpeciesRow]":
    """Load the live seed roster, or parse an explicitly supplied legacy C# file."""
    if path.is_dir():
        return [_live_row(record) for record in load_live_records(path)]
    return _load_legacy_catalog(path)
